#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DEFAULT_PATCHBAY="$ROOT/examples/json-massive/bar-cardinality.edn"
DEFAULT_BAR_WINDOW=100000000
BIN="${BIN:-$ROOT/build/monoblok}"
PATCHBAY_SET=0
if [[ ${PATCHBAY+x} ]]; then
    PATCHBAY_SET=1
else
    PATCHBAY="$DEFAULT_PATCHBAY"
fi
MARKETS="${MARKETS:-20}"
SYMBOLS="${SYMBOLS:-5000}"
TICKS="${TICKS:-1}"
BAR_WINDOW="${BAR_WINDOW:-$DEFAULT_BAR_WINDOW}"
SAMPLE_INTERVAL="${SAMPLE_INTERVAL:-0.05}"

if [[ ! -x "$BIN" ]]; then
    echo "monoblok binary not found or not executable: $BIN" >&2
    echo "Set BIN=/path/to/monoblok or build with: cmake --build build --target monoblok" >&2
    exit 1
fi

if [[ ! "$MARKETS" =~ ^[0-9]+$ || ! "$SYMBOLS" =~ ^[0-9]+$ || ! "$TICKS" =~ ^[0-9]+$ || ! "$BAR_WINDOW" =~ ^[0-9]+$ ]]; then
    echo "MARKETS, SYMBOLS, TICKS, and BAR_WINDOW must be positive integers" >&2
    exit 1
fi
if (( MARKETS < 1 || SYMBOLS < 1 || TICKS < 1 || BAR_WINDOW < 1 )); then
    echo "MARKETS, SYMBOLS, TICKS, and BAR_WINDOW must be positive integers" >&2
    exit 1
fi

TMPDIR="${TMPDIR:-/tmp}"
RUN_DIR=""
cleanup() {
    if [[ -n "$RUN_DIR" ]]; then
        rm -rf "$RUN_DIR"
    fi
}
trap cleanup EXIT

make_run_dir() {
    if [[ -z "$RUN_DIR" ]]; then
        RUN_DIR="$(mktemp -d "$TMPDIR/monoblok-bar-cardinality.XXXXXX")"
    fi
}

BAR_NOTE="$BAR_WINDOW ticks"
if (( PATCHBAY_SET == 0 )) && [[ "$BAR_WINDOW" != "$DEFAULT_BAR_WINDOW" ]]; then
    make_run_dir
    PATCHBAY="$RUN_DIR/bar-cardinality.edn"
    {
        printf '; Generated by measure-bar-cardinality.sh for BAR_WINDOW=%s.\n\n' "$BAR_WINDOW"
        printf '(on "T.*.*"\n'
        printf '  (when (json-get "p" payload)\n'
        printf '    (bar! %s (json-get "p" payload))))\n' "$BAR_WINDOW"
    } >"$PATCHBAY"
elif (( PATCHBAY_SET != 0 )); then
    BAR_NOTE="from custom PATCHBAY"
fi

TIME_CMD=()
TIME_NOTE="sampling RSS with ps"
if [[ -x /usr/bin/time ]]; then
    if /usr/bin/time -l true >/dev/null 2>&1; then
        TIME_CMD=(/usr/bin/time -l)
        TIME_NOTE="BSD time: maximum resident set size is bytes"
    elif /usr/bin/time -v true >/dev/null 2>&1; then
        TIME_CMD=(/usr/bin/time -v)
        TIME_NOTE="GNU time: Maximum resident set size is KiB"
    fi
fi

SUBJECTS=$(( MARKETS * SYMBOLS ))
ROWS=$(( SUBJECTS * TICKS ))
TICK_WORD="ticks"
if (( TICKS == 1 )); then
    TICK_WORD="tick"
fi

printf 'bar cardinality probe\n' >&2
printf '  patchbay:  %s\n' "$PATCHBAY" >&2
printf '  binary:    %s\n' "$BIN" >&2
printf '  subjects:  %d markets * %d symbols = %d bar slots\n' "$MARKETS" "$SYMBOLS" "$SUBJECTS" >&2
printf '  rows:      %d %s per subject = %d input rows\n' "$TICKS" "$TICK_WORD" "$ROWS" >&2
printf '  window:    %s\n' "$BAR_NOTE" >&2
printf '  rss note:  %s\n\n' "$TIME_NOTE" >&2

generate_rows() {
    awk -v markets="$MARKETS" -v symbols="$SYMBOLS" -v ticks="$TICKS" '
        BEGIN {
            for (m = 0; m < markets; m += 1) {
                market = sprintf("M%02d", m)
                for (s = 0; s < symbols; s += 1) {
                    sym = sprintf("S%05d", s)
                    base = 50.0 + (s % 500) * 0.25 + m
                    for (t = 0; t < ticks; t += 1) {
                        price = base + t * 0.01
                        printf "T.%s.%s|{\"ev\":\"T\",\"sym\":\"%s\",\"p\":%.4f,\"s\":%d}\n", market, sym, sym, price, 1 + t
                    }
                }
            }
        }
    '
}

if (( ${#TIME_CMD[@]} > 0 )); then
    generate_rows | "${TIME_CMD[@]}" "$BIN" --soundcheck --soundcheck-linger-ms 0 "$PATCHBAY" >/dev/null
else
    make_run_dir
    INPUT="$RUN_DIR/input.rows"

    generate_rows >"$INPUT"
    "$BIN" --soundcheck --soundcheck-linger-ms 0 "$PATCHBAY" <"$INPUT" >/dev/null &
    MB_PID=$!

    PEAK_RSS_KIB=0
    sample_rss() {
        RSS_KIB="$(ps -o rss= -p "$MB_PID" 2>/dev/null | awk 'NF { print $1; exit }' || true)"
        if [[ "$RSS_KIB" =~ ^[0-9]+$ ]] && (( RSS_KIB > PEAK_RSS_KIB )); then
            PEAK_RSS_KIB="$RSS_KIB"
        fi
    }

    sample_rss
    while kill -0 "$MB_PID" 2>/dev/null; do
        sample_rss
        sleep "$SAMPLE_INTERVAL"
    done

    set +e
    wait "$MB_PID"
    MB_STATUS=$?
    set -e

    if (( PEAK_RSS_KIB > 0 )); then
        printf '\nsampled max RSS: %d KiB\n' "$PEAK_RSS_KIB" >&2
    else
        printf '\nsampled max RSS: unavailable (ps returned no RSS samples)\n' >&2
    fi
    exit "$MB_STATUS"
fi
